CREATE DATABASE AGENDA

USE AGENDA
go
create table CONTACTOS(
ID int IDENTITY(1,1) NOT NULL primary key,
NOMBRES NVARCHAR(30) NOT NULL,
APELLIDOS NVARCHAR(40) NOT NULL,
CEDULA NVARCHAR(30) NOT NULL,
CORREO NVARCHAR(40),
TELEFONO_1 NVARCHAR(25) NOT NULL,
TELEFONO_2 NVARCHAR(25),
DIRECCION nvarchar(123) null
)
GO
insert into CONTACTOS values('David Elias', 'Solano Castro','402-0077109-1', '20187203@itla.edu.do','829-821-0513','', 'Villa Mella')
select * from CONTACTOS
------STORE PROCEDURE BUSCAR CONTACTO-----------
go
CREATE PROC SP_BUSCARCONTACTO 
@BUSCAR NVARCHAR(30)
AS
SELECT * FROM CONTACTOS
WHERE NOMBRES LIKE @BUSCAR + '%'

------PROCEDIMIENTO INSERTAR PERSONA--------
GO
CREATE PROC SP_INSERTARCONTACTO
@NOMBRES NVARCHAR(30),
@APELLIDOS NVARCHAR(40),
@CEDULA NVARCHAR(30),
@CORREO NVARCHAR(40),
@TELEFONO1 NVARCHAR (25),
@TELEFONO2 NVARCHAR(25),

@DIRECCION NVARCHAR(75)
AS
INSERT INTO CONTACTOS VALUES(@NOMBRES, @APELLIDOS, @CEDULA, @CORREO, @TELEFONO1, @TELEFONO2 , @DIRECCION)

------PROCEDIMIENTO EDITAR PERSONA------------
GO
CREATE PROC SP_EDITARCONTACTO
@ID INT,
@NOMBRES NVARCHAR(30),
@APELLIDOS NVARCHAR(40),
@CEDULA NVARCHAR(30),
@CORREO NVARCHAR(40),
@TELEFONO1 NVARCHAR (25),
@TELEFONO2 NVARCHAR(25),

@DIRECCION NVARCHAR(75)
AS
UPDATE CONTACTOS SET NOMBRES = @NOMBRES, APELLIDOS = @APELLIDOS, CEDULA = @CEDULA ,CORREO = @CORREO, TELEFONO_1 = @TELEFONO1,TELEFONO_2 = @TELEFONO2,
 DIRECCION = @DIRECCION
WHERE ID = @ID

-------PROCEDIMIENTO ELIMINAR PERSONA---------
GO
CREATE PROC SP_ELIMINARCONTACTO
@ID INT 
AS
DELETE CONTACTOS 
WHERE ID = @ID
go
